name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - run: echo "- Lint the code and run unit tests"

  build:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v6.0.1
      - run: echo "- Build the artifact"

  test-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6.0.1
      - run: echo "- Simulate and test the artifact"

  deploy-development:
    runs-on: ubuntu-latest
    environment: Development
    needs: test-artifact
    steps:
      - run: echo "- Auto-deploy the artifact to the development environment"

  deploy-staging:
    runs-on: ubuntu-latest
    environment: Staging
    needs: [deploy-development, test-artifact] 
    
    steps:
      - run: |
          echo "After development environment is deployed..."
          echo "and after the artifact tests have passed..."
          echo "- Auto-deploy the artifact to the staging environment"

  test-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - run: echo "- Test the staging environment"

  deploy-production:
    runs-on: ubuntu-latest
    environment: Production
    needs: test-staging
    steps:
      - run: |
          echo "After staging environment is deployed..."
          echo "and after the staging tests have passed..."
          echo "require a review before deploying to the production environment, then..."
          echo "- Deploy the artifact to the production environment"

  test-production:
    runs-on: ubuntu-latest
    needs: deploy-production
    steps:
      - run: echo "- Test the artifact in the production environment"
      - run: echo "# All tests and deployments have completed successfully!"
